<?php
date_default_timezone_set('Asia/Ho_Chi_Minh');
return [
    'appName' => 'Wibet',
    'homeUrl' => '/site/index',
    'seasonName' => 'EURO 2024',
    'team' => 'Wibet Team',
    'minBetTimes' => 4,
    'startingMoney' => 100,
    'minPayMoney' => 100,
    'maxPayMoney' => 800,
    'minBetMoney' => 50,
    'maxRefillTimes' => 4,
    'groupChat' => 'https://join.skype.com/tMRrQSXDthKA',
    'adminChat' => 'skype:live:.cid.569524b1769cc753?chat',
    'adminName' => 'Giàu Võ',
    'adminEmail' => 'wibetteam@gmail.com', //Wibet@12345
    'senderName' => 'Wibet',
    'currency' => 'w',
    'currencyName' => 'Wicoin',
    'currencyReal' => '₫',
    'currencyRealName' => 'VND',
    'bankName' => 'VO NGOC GIAU',
    'bankID' => '1440216948',
    'bankBrand' => 'BIDV CN TN TpHCM',
    'bankLink' => '#',
    'momoNumb' => '0834020737',
    'momoName' => 'Võ Ngọc Giàu',
    'momoLink' => 'https://me.momo.vn/dQIQTQt1U1fwI5tGI2FxUE/Vyb83z4l1B7ravA',
    'giftItem' => 'Móc Khoá',
    'totalAmount' => 22600000,
    'mtRate' => 10,
    'adjRate' => 5,
    'p1Rate' => 25,
    'p1Count' => 1,
    'p2Rate' => 20,
    'p2Count' => 1,
    'p3Rate' => 10,
    'p3Count' => 2,
    'p4Rate' => 5,
    'p4Count' => 4,
    'p5Rate' => 0,
    'p5Count' => 5,
];
